=== stctheproducer/docker-containers/webhook/webhook.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://github.com/stctheproducer/docker-containers/webhook/webhook.schema.json",
  "title": "Webhook",
  "description": "A unique entry in the webhook.",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "A unique ID that specifies the webhook."
      },
      "execute-command": {
        "type": "string"
      },
      "command-working-directory": {
        "type": "string"
      },
      "response-message": {
        "type": "string"
      },
      "response-headers": {
        "type": "array",
        "items": {
          "$ref": "#/$defs/response-header"
        }
      },
      "http-methods": {
        "type": "array",
        "items": {
          "type": "string",
          "enum": ["POST", "GET"]
        }
      },
      "include-command-output-in-response": {
        "type": "boolean"
      },
      "include-command-output-in-response-on-error": {
        "type": "boolean"
      },
      "pass-arguments-to-command": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "source": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": ["source", "name"]
        }
      },
      "trigger-rule": {
        "type": "object",
        "properties": {
          "and": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "match": {
                  "$ref": "#/$defs/match"
                }
              }
            }
          },
          "or": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "match": {
                  "$ref": "#/$defs/match"
                }
              }
            }
          },
          "not": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "match": {
                  "$ref": "#/$defs/match"
                }
              }
            }
          }
        }
      },
      "trigger-rule-mismatch-http-response-code": {
        "type": "number"
      }
    },
    "required": ["id"]
  },
  "uniqueItems": true,
  "$defs": {
    "response-header": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["name", "value"]
    },
    "match": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "ip-range": {
          "type": "string"
        },
        "regex": {
          "type": "string"
        },
        "secret": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "parameter": {
          "type": "object",
          "properties": {
            "source": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": ["source", "name"]
        }
      },
      "required": ["type", "parameter"]
    },
    "and": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "match": {
            "$ref": "#/$defs/match"
          }
        }
      }
    },
    "or": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "match": {
            "$ref": "#/$defs/match"
          }
        }
      }
    },
    "not": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "match": {
            "$ref": "#/$defs/match"
          }
        }
      }
    }
  }
}

=== stctheproducer/docker-containers/webhook/examples/hooks.drone-webhook.json
{
  "id": "test-webhook",
  "execute-command": "/opt/scripts/",
  "command-working-directory": "/opt/deploy",
  "response-message": "I got the payload!",
  "response-headers": [
    {
      "name": "Access-Control-Allow-Origin",
      "value": "*"
    }
  ],
  "trigger-rule": {
    "match": {
      "type": "payload-hash-sha256",
      "secret": "{{ getenv \"DRONE_WEBHOOK_SECRET\" | js }}",
      "parameter": {
        "source": "header",
        "name": "Authorization"
      }
    }
  }
}

=== stctheproducer/docker-containers/webhook/examples/hooks.pull-example.json
[
	{
		"id": "pull-request-webhook",
		"execute-command": "/opt/scripts/deploy.sh",
		"command-working-directory": "/opt/deploy",
		"response-message": "Executing deploy script...",
		"response-headers": [
			{
				"name": "Access-Control-Allow-Origin",
				"value": "*"
			}
		],
		"trigger-rule": {
			"and": [
				{
					"match": {
						"type": "payload-hash-sha1",
						"secret": "mysecret",
						"parameter": {
							"source": "header",
							"name": "X-Hub-Signature"
						}
					}
				},
				{
					"match": {
						"type": "value",
						"value": "closed",
						"parameter": {
							"source": "payload",
							"name": "action"
						}
					}
				},
        {
          "match": {
            "type": "value",
            "value": "true",
            "parameter": {
              "source": "payload",
              "name": "pull_request.merged"
            }
          }
        }
			]
		}
	}
]
